[package]
name = "puppet-fmt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
argh = "0.1"
rustc-hash = "2.1"
tree-sitter = "0.24"
tree-sitter-puppet = "1.3"

[profile.release]
strip = "symbols"
lto = "fat"
opt-level = 3
